import type { RequestItem } from "./types";

// Mock data for local development when no API is configured
export const MOCK_REQUESTS: RequestItem[] = [
	{
		requestId: "CR_h83jjnomGJXU",
		type: "hk-retrieval",
		step: "delivered",
		organization: "canary",
		deploymentStage: "prod",
		environment: "lambda",
		automated: true,
		startedAt: "2026-03-23T14:32:45.123Z",
		duration: 45230,
		countryCode: "HK",
		documentType: "C.R. Extract",
		companyId: "12345678",
		companyName: "Acme Ltd",
		ttl: 1806950365,
		_stage: "prod",
	},
	{
		requestId: "CR_k92mmqrtHLZV",
		type: "hk-retrieval",
		step: "manual",
		organization: "canary",
		deploymentStage: "prod",
		environment: "lambda",
		automated: false,
		startedAt: "2026-03-23T13:10:22.456Z",
		duration: 12400,
		countryCode: "HK",
		documentType: "C.R. Extract",
		companyId: "87654321",
		error: {
			step: "retrieved",
			message: "Login failed: incorrect credentials",
			stack:
				"Error: Login failed at LoginHandler.execute (/src/steps/login.ts:42)",
		},
		debugUrl: "https://s3.amazonaws.com/debug/screenshot-k92mm.png",
		ttl: 1806950365,
		_stage: "prod",
	},
	{
		requestId: "CR_a11bbnntPQRS",
		type: "sg-retrieval",
		step: "processing",
		organization: "production",
		deploymentStage: "staging",
		environment: "lambda",
		automated: true,
		startedAt: "2026-03-23T12:05:00.000Z",
		countryCode: "SG",
		documentType: "Business Profile",
		companyId: "11223344",
		ttl: 1806950365,
		_stage: "staging",
	},
	{
		requestId: "CR_z77xxwwvMNOP",
		type: "hk-retrieval",
		step: "initiated",
		organization: "canary",
		deploymentStage: "staging",
		environment: "lambda",
		automated: true,
		startedAt: "2026-03-22T09:15:30.789Z",
		countryCode: "MY",
		documentType: "SSM Extract",
		companyId: "55667788",
		ttl: 1806950365,
		_stage: "staging",
	},
	{
		requestId: "CR_p55qqrrsKLMN",
		type: "hk-retrieval",
		step: "delivered",
		organization: "production",
		deploymentStage: "prod",
		environment: "lambda",
		automated: true,
		startedAt: "2026-03-21T16:45:12.321Z",
		duration: 32100,
		countryCode: "HK",
		documentType: "Annual Return",
		companyId: "99001122",
		ttl: 1806950365,
		_stage: "prod",
	},
];
