import { RequestItem } from "./types";

// Mock data for local development when no API is configured
export const MOCK_REQUESTS: RequestItem[] = [
  {
    requestId: "CR_h83jjnomGJXU",
    type: "cra-request",
    step: "completed",
    organization: "canary",
    deploymentStage: "prod",
    environment: "lambda",
    automated: true,
    startedAt: "2026-03-23T14:32:45.123Z",
    duration: 45230,
    countryCode: "HK",
    documentType: "C.R. Extract",
    companyId: "12345678",
    ttl: 1806950365,
  },
  {
    requestId: "CR_k92mmqrtHLZV",
    type: "cra-request",
    step: "failed",
    organization: "canary",
    deploymentStage: "prod",
    environment: "lambda",
    automated: true,
    startedAt: "2026-03-23T13:10:22.456Z",
    duration: 12400,
    countryCode: "HK",
    documentType: "C.R. Extract",
    companyId: "87654321",
    failedStep: "login",
    error: {
      step: "login",
      message: "Login failed: incorrect credentials",
      stack: "Error: Login failed at LoginHandler.execute (/src/steps/login.ts:42)",
    },
    debugUrl: "https://s3.amazonaws.com/debug/screenshot-k92mm.png",
    ttl: 1806950365,
  },
  {
    requestId: "CR_a11bbnntPQRS",
    type: "doc-request",
    step: "in-progress",
    organization: "production",
    deploymentStage: "staging",
    environment: "lambda",
    automated: false,
    startedAt: "2026-03-23T12:05:00.000Z",
    duration: 0,
    countryCode: "SG",
    documentType: "Business Profile",
    companyId: "11223344",
    ttl: 1806950365,
  },
  {
    requestId: "CR_z77xxwwvMNOP",
    type: "cra-request",
    step: "pending",
    organization: "canary",
    deploymentStage: "dev",
    environment: "local",
    automated: true,
    startedAt: "2026-03-22T09:15:30.789Z",
    duration: 0,
    countryCode: "MY",
    documentType: "SSM Extract",
    companyId: "55667788",
    ttl: 1806950365,
  },
  {
    requestId: "CR_p55qqrrsKLMN",
    type: "doc-request",
    step: "completed",
    organization: "production",
    deploymentStage: "prod",
    environment: "lambda",
    automated: true,
    startedAt: "2026-03-21T16:45:12.321Z",
    duration: 32100,
    countryCode: "HK",
    documentType: "Annual Return",
    companyId: "99001122",
    ttl: 1806950365,
  },
];
